# Generated by Django 3.1.5 on 2021-01-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
