# Generated by Django 3.1.5 on 2021-01-26 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0002_auto_20210126_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Name',
            field=models.ForeignKey(default='', max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
