# Generated by Django 3.1.5 on 2021-01-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Name',
            field=models.CharField(max_length=20),
        ),
    ]
